openapi: '3.0.0'
info:
  version: 0.0.3
  title: Zam.io Сгенерировать приватный ключ кошелька Zam в авторизованной зоне
  description: "Zam.io Сгенерировать приватный ключ кошелька Zam в авторизованной зоне"
servers:
  - url: https://zam.io

paths:
  '/api/auth/privateKey':
    post:
      summary: Сгенерировать приватный ключ кошелька Zam в авторизованной зоне
      security:
        - bearerAuth: [ ]

      responses:
        '200':
          description: Успешная операция
          content:
            application/json:
              schema:
                properties:
                  meta:
                    $ref: '#/components/schemas/Meta'
                  data:
                    $ref: '#/components/schemas/PrivateKeyResponseData'
        '400':
          description: Некорректный формат входных параметров
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExceptionResult'
        '408':
          description: Время ожидания истекло
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExceptionResult'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExceptionResult'
        '503':
          description: Сервис недоступен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExceptionResult'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Meta:
      type: object
      description: Метаинформация об ответе
      required:
        - status
        - message
      properties:
        status:
          type: string
          description: Текстовый код исключения
          enum:
            - 'OK' #statuscode=200
          example: 'OK'
        message:
          type: string
          description: Дополнительная информация
          enum:
            - 'Операция выполнена' #statuscode=200
          example: 'Операция выполнена'
        description:
          type: string
          description: Пользовательская информация о результате выполнения метода
          example: 'Запрос получен. Ожидайте выполнения'
    PrivateKeyResponseData:
      type: object
      description: приватный ключ кошелька Zam
      required:
        - privateKey
      properties:
        privateKey:
          type: string
          description: приватный ключ кошелька Zam
    ExceptionResult:
      type: object
      properties:
        meta:
          $ref: '#/components/schemas/ExceptionMeta'
        data:
          type: object
    ExceptionMeta:
      type: object
      description: Метаинформация об ответе
      required:
        - status
        - message
      properties:
        status:
          type: string
          description: Текстовый код исключения
          enum:
            - 'BAD_REQUEST' #statuscode=400
            - 'UNAUTHORIZED' #STATUSCODE=401
            - 'FORBIDDEN' #STATUSCODE=403
            - 'NOT_FOUND' #STATUSCODE=404
            - 'REQUEST_TIMEOUT' #STATUSCODE=408
            - 'ERROR' #statuscode IN [500,503]
          example: 'ERROR'
        message:
          type: string
          description: Дополнительная информация
          enum:
            - 'Набор параметров или тип указаны неверно' #statuscode=400
            - 'Ошибка авторизации' #statuscode=401
            - 'Недостаточно прав для получения информации' #statuscode=403
            - 'Данные не найдены' #statuscode=404
            - 'Время ожидания истекло' #statuscode=408
            - 'Внутренняя ошибка сервера' #statuscode=500
            - 'Сервис недоступен' #statuscode=503
          example: 'Сервис недоступен'
        description:
          type: string
          description: Пользовательская информация о результате выполнения метода
